<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="eon-swapnili" name="lasvegasmarket_PROD.EvenntsAndWebinar" tests="2" failures="0" timestamp="9 Jan 2024 11:43:49 GMT" time="98.336" errors="1">
  <testcase name="TS003_VerifyIMCEventsCalendarViewTest" time="64.956" classname="lasvegasmarket_PROD.EvenntsAndWebinar"/>
  <testcase name="TS004_VerifyIMCEventsEventsListTest" time="33.380" classname="lasvegasmarket_PROD.EvenntsAndWebinar">
    <error type="java.lang.AssertionError" message="expected [35] but found [50]">
      <![CDATA[java.lang.AssertionError: expected [35] but found [50]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:370)
	at org.testng.Assert.assertEquals(Assert.java:380)
	at lasvegasmarket_PROD.EvenntsAndWebinar.TS004_VerifyIMCEventsEventsListTest(EvenntsAndWebinar.java:448)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- TS004_VerifyIMCEventsEventsListTest -->
</testsuite> <!-- lasvegasmarket_PROD.EvenntsAndWebinar -->
